[programs.localnet]
lucky_num = "8BQunCRwyBZ3EaPP4bmCraTWhVvazrajNR3CtTM7P5rT"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/justinlee/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
